--- # Ansible initial setup -  Copy ssh key to remote host  
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:

  - name: creat directory if not exist 
    file:
     path: /root/.ssh
     state: directory
     mode: 0755

  - name: copying file to remote host
    copy:
     src: /root/.ssh/newkey.pub
     dest: /root/.ssh/
     owner: root
     group: root
     mode: 0644

  - name: Setup authorized key from copied file
    authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', '/root/.ssh/newkey.pub') }}"

 

